### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by oranje19** [oranje19/Grande#2]
- [x] Users can sign up, sign in, and log out

- [x]  Users can use a demo login to try the site

- [x]  Users can't use certain features without logging in (creating stories & claps)

**Comment by Vanchen07** [comment]
-when I try to sign up I get this error: "Uncaught TypeError: this.props.errors.map is not a function"
- I'm also not able to log in as demo user

**Comment by oranje19** [comment]
> -when I try to sign up I get this error: "Uncaught TypeError: this.props.errors.map is not a function"
> 
> * I'm also not able to log in as demo user

Fixed it. Updated on heroku

**Comment by Vanchen07** [comment]
Looks good, thank you!
